/* Generated by AN DISI Unibo */ 
package it.unibo.maitre

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maitre ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[MAITRE]: starts...")
						itunibo.maitre.maitreGUI.init(myself)
					}
					 transition( edgeName="goto",targetState="sendingPrepare", cond=doswitch() )
				}	 
				state("sendingPrepare") { //this:State
					action { //it:State
						println("[MAITRE]: i'm in sendingPrepare")
						itunibo.maitre.maitreGUI.enableOnlyPrepare(  )
					}
					 transition(edgeName="t018",targetState="waitingPrepCompleted",cond=whenDispatch("prepareSended"))
				}	 
				state("waitingPrepCompleted") { //this:State
					action { //it:State
						itunibo.maitre.maitreGUI.enableOnlySR(  )
						forward("modelUpdate", "modelUpdate(maitre,prepare)" ,"maitremodel" ) 
						forward("prepare", "prepare" ,"mindbutler" ) 
						println("[MAITRE]: waiting for a prepareCompleted...")
					}
					 transition(edgeName="t019",targetState="sendingAC",cond=whenDispatch("modelChanged"))
					transition(edgeName="t020",targetState="updateP",cond=whenEvent("updateMaitre"))
				}	 
				state("sendingAC") { //this:State
					action { //it:State
						println("[MAITRE]: i'm in sendingAC")
						itunibo.maitre.maitreGUI.enableOnlyAC(  )
					}
					 transition(edgeName="t021",targetState="waitingAddFoodCompleted",cond=whenDispatch("addFoodSended"))
					transition(edgeName="t022",targetState="waitingClearCompleted",cond=whenDispatch("clearSended"))
				}	 
				state("waitingAddFoodCompleted") { //this:State
					action { //it:State
						itunibo.maitre.maitreGUI.enableOnlySR(  )
						forward("modelUpdate", "modelUpdate(maitre,addFood)" ,"maitremodel" ) 
						forward("addFood", "addFood(taralli,5)" ,"mindbutler" ) 
						println("[MAITRE]: waiting for an addFoodCompleted...")
					}
					 transition(edgeName="t023",targetState="sendingAC",cond=whenDispatch("modelChanged"))
					transition(edgeName="t024",targetState="updateA",cond=whenEvent("updateMaitre"))
				}	 
				state("waitingClearCompleted") { //this:State
					action { //it:State
						itunibo.maitre.maitreGUI.enableOnlySR(  )
						forward("modelUpdate", "modelUpdate(maitre,clear)" ,"maitremodel" ) 
						forward("clear", "clear" ,"mindbutler" ) 
						println("[MAITRE]: waiting for a clearCompleted...")
					}
					 transition(edgeName="t025",targetState="sendingPrepare",cond=whenDispatch("modelChanged"))
					transition(edgeName="t026",targetState="updateC",cond=whenEvent("updateMaitre"))
				}	 
				state("updateP") { //this:State
					action { //it:State
						println("[MAITRE]: i'm in updateP")
					}
					 transition( edgeName="goto",targetState="waitingPrepCompleted", cond=doswitch() )
				}	 
				state("updateA") { //this:State
					action { //it:State
						println("[MAITRE]: i'm in updateA")
					}
					 transition( edgeName="goto",targetState="waitingAddFoodCompleted", cond=doswitch() )
				}	 
				state("updateC") { //this:State
					action { //it:State
						println("[MAITRE]: i'm in updateC")
					}
					 transition( edgeName="goto",targetState="waitingClearCompleted", cond=doswitch() )
				}	 
			}
		}
}
