/* Generated by AN DISI Unibo */ 
package it.unibo.modelmanagermaitre

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Modelmanagermaitre ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[MODELMANAGER MAITRE]: Started...")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("[MODELMANAGER MAITRE]: Sono in waitCmd")
					}
					 transition(edgeName="t058",targetState="handleCommand",cond=whenDispatch("stateChanged"))
					transition(edgeName="t059",targetState="handleCommand",cond=whenDispatch("taskChanged"))
				}	 
				state("handleCommand") { //this:State
					action { //it:State
						println("[MODELMANAGER MAITRE]: Sono in waitCmd")
						if( checkMsgContent( Term.createTerm("stateChanged(DEVICE,STATE)"), Term.createTerm("stateChanged(maitre,STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
						if( checkMsgContent( Term.createTerm("taskChanged(DEVICE,TASK)"), Term.createTerm("taskChanged(maitre,TASK)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
