/* Generated by AN DISI Unibo */ 
package it.unibo.butler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Butler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var numeroOstacoli=0; var positive=false; var DishCarrello=0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[BUTLER]: Started...")
					}
					 transition( edgeName="goto",targetState="forwardStep", cond=doswitch() )
				}	 
				state("forwardStep") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in forwardStep")
					}
					 transition(edgeName="t02",targetState="backtracking",cond=whenEvent("obstacle"))
				}	 
				state("backtracking") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in backtracking")
						forward("robotCmd", "robotCmd(butler,s)" ,"basicrobot" ) 
					}
					 transition(edgeName="t03",targetState="turnLeft",cond=whenDispatch("movementCompleted"))
				}	 
				state("turnLeft") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in turnLeft")
						numeroOstacoli++
					}
					 transition( edgeName="goto",targetState="waitPrepare", cond=doswitchGuarded({(numeroOstacoli==4)}) )
					transition( edgeName="goto",targetState="forwardStep", cond=doswitchGuarded({! (numeroOstacoli==4)}) )
				}	 
				state("waitPrepare") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in waitPrepare")
					}
					 transition(edgeName="t04",targetState="calcPathToPantryA1",cond=whenDispatch("prepare"))
				}	 
				state("calcPathToPantryA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToPantryA1")
					}
					 transition( edgeName="goto",targetState="execPathToPantryA1", cond=doswitch() )
				}	 
				state("execPathToPantryA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToPantryA1")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t05",targetState="prepTakingDishA1",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepTakingDishA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepTakingDishA1")
						DishCarrello=5
						forward("pantryTakeDish", "takeDish(5)" ,"pantry" ) 
					}
					 transition( edgeName="goto",targetState="calcPathToTableA1", cond=doswitch() )
				}	 
				state("calcPathToTableA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToTableA1")
					}
					 transition( edgeName="goto",targetState="execPathToTableA1", cond=doswitch() )
				}	 
				state("execPathToTableA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToTableA1")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t06",targetState="prepPuttingDishA1",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepPuttingDishA1") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepPuttingDishA1")
						forward("putElement", "putElement(dish,CODE,$DishCarrello)" ,"table" ) 
					}
					 transition( edgeName="goto",targetState="calcPathToFridgeA2", cond=doswitch() )
				}	 
				state("calcPathToFridgeA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToFridgeA2")
					}
					 transition( edgeName="goto",targetState="execPathToFridgeA2", cond=doswitch() )
				}	 
				state("execPathToFridgeA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToFridgeA2")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t07",targetState="prepTakingFoodA2",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepTakingFoodA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepTakingFoodA2")
					}
					 transition( edgeName="goto",targetState="calcPathToTableA2", cond=doswitch() )
				}	 
				state("calcPathToTableA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToTableA2")
					}
					 transition( edgeName="goto",targetState="execPathToTableA2", cond=doswitch() )
				}	 
				state("execPathToTableA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToTableA2")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t08",targetState="prepPuttingFoodA2",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepPuttingFoodA2") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepPuttingFoodA2")
					}
					 transition( edgeName="goto",targetState="calcPathToRHPrep", cond=doswitch() )
				}	 
				state("calcPathToRHPrep") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToRHPrep")
					}
					 transition( edgeName="goto",targetState="execPathToRHPrep", cond=doswitch() )
				}	 
				state("execPathToRHPrep") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToRHPrep")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t09",targetState="prepareComplete",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepareComplete") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepareComplete")
						forward("prepareCompleted", "prepareCompleted" ,"maitre" ) 
					}
					 transition( edgeName="goto",targetState="waitAC", cond=doswitch() )
				}	 
				state("waitAC") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in waitAC")
					}
					 transition(edgeName="t010",targetState="makeQuery",cond=whenDispatch("addFood"))
					transition(edgeName="t011",targetState="calcPathToTableA4",cond=whenDispatch("clear"))
				}	 
				state("makeQuery") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in makeQuery")
						if( checkMsgContent( Term.createTerm("addFood(FOODCODE,QNT)"), Term.createTerm("addFood(FOODCODE,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("query", "query(${payloadArg(0)},${payloadArg(1)})" ,"fridge" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitAnswer", cond=doswitch() )
				}	 
				state("waitAnswer") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in waitAnswer")
					}
					 transition(edgeName="t012",targetState="checkAnswer",cond=whenDispatch("answer"))
				}	 
				state("checkAnswer") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in checkAnswer")
						if( checkMsgContent( Term.createTerm("answer(FOODCODE,ANS)"), Term.createTerm("answer(FOODCODE,ANS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								positive=payloadArg(1).equals("yes")
						}
					}
					 transition( edgeName="goto",targetState="calcPathToFridgeA7", cond=doswitchGuarded({positive}) )
					transition( edgeName="goto",targetState="calcPathToRHAdd", cond=doswitchGuarded({! positive}) )
				}	 
				state("calcPathToFridgeA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToFridgeA7")
					}
					 transition( edgeName="goto",targetState="execPathToFridgeA7", cond=doswitch() )
				}	 
				state("execPathToFridgeA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToFridgeA7")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t013",targetState="prepTakingFoodA7",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepTakingFoodA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepTakingFoodA7")
					}
					 transition( edgeName="goto",targetState="calcPathToTableA7", cond=doswitch() )
				}	 
				state("calcPathToTableA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToTableA7")
					}
					 transition( edgeName="goto",targetState="execPathToTableA7", cond=doswitch() )
				}	 
				state("execPathToTableA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToTableA7")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t014",targetState="prepPuttingFoodA7",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepPuttingFoodA7") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepPuttingFoodA7")
					}
					 transition( edgeName="goto",targetState="calcPathToRHAdd", cond=doswitch() )
				}	 
				state("calcPathToRHAdd") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToRHAdd")
					}
					 transition( edgeName="goto",targetState="execPathToRHAdd", cond=doswitch() )
				}	 
				state("execPathToRHAdd") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToRHAdd")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t015",targetState="addComplete",cond=whenDispatch("routeCompleted"))
				}	 
				state("addComplete") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in addComplete")
						forward("addFoodCompleted", "addFoodCompleted" ,"maitre" ) 
					}
					 transition( edgeName="goto",targetState="waitAC", cond=doswitch() )
				}	 
				state("calcPathToTableA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToTableA4")
					}
					 transition( edgeName="goto",targetState="execPathToTableA4", cond=doswitch() )
				}	 
				state("execPathToTableA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToTableA4")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t016",targetState="prepTakingFoodA4",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepTakingFoodA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepTakingFoodA4")
					}
					 transition( edgeName="goto",targetState="calcPathToFridgeA4", cond=doswitch() )
				}	 
				state("calcPathToFridgeA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToFridgeA4")
					}
					 transition( edgeName="goto",targetState="execPathToFridgeA4", cond=doswitch() )
				}	 
				state("execPathToFridgeA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToFridgeA4")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t017",targetState="prepPuttingFoodA4",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepPuttingFoodA4") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepPuttingFoodA4")
					}
					 transition( edgeName="goto",targetState="calcPathToTableA5", cond=doswitch() )
				}	 
				state("calcPathToTableA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToTableA5")
					}
					 transition( edgeName="goto",targetState="execPathToTableA5", cond=doswitch() )
				}	 
				state("execPathToTableA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToTableA5")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t018",targetState="prepTakingDishA5",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepTakingDishA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepTakingDishA5")
					}
					 transition( edgeName="goto",targetState="calcPathToDishawasherA5", cond=doswitch() )
				}	 
				state("calcPathToDishawasherA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToDishawasherA5")
					}
					 transition( edgeName="goto",targetState="execPathToDishawasherA5", cond=doswitch() )
				}	 
				state("execPathToDishawasherA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToDishawasherA5")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t019",targetState="prepPuttingDishA5",cond=whenDispatch("routeCompleted"))
				}	 
				state("prepPuttingDishA5") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in prepPuttingDishA5")
					}
					 transition( edgeName="goto",targetState="calcPathToRHClear", cond=doswitch() )
				}	 
				state("calcPathToRHClear") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in calcPathToRHClear")
					}
					 transition( edgeName="goto",targetState="execPathToRHClear", cond=doswitch() )
				}	 
				state("execPathToRHClear") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in execPathToRHClear")
						forward("startPlanning", "startPlanning" ,"execroute" ) 
					}
					 transition(edgeName="t020",targetState="clearComplete",cond=whenDispatch("movementCompleted"))
				}	 
				state("clearComplete") { //this:State
					action { //it:State
						println("[BUTLER]: Sono in clearComplete")
						forward("clearCompleted", "clearCompleted" ,"maitre" ) 
					}
					 transition( edgeName="goto",targetState="waitPrepare", cond=doswitch() )
				}	 
			}
		}
}
