/* Generated by AN DISI Unibo */ 
package it.unibo.movementhandler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Movementhandler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var input=""
				var startF = 0L
				var endF = 0L
		
				var ForwardTime=-1L
				var TurnLeftTime=-1L
				var TurnRightTime=-1L
				var TuningTime=-1L
				var DifferenceLimitTime=-1L
		
				var TimeToWait=-1L
		
				var temp=""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[MOVEMENT HANDLER]: Started...")
						solve("consult('movementConfig.pl')","") //set resVar	
						solve("time(forw4rd,X)","") //set resVar	
						if(currentSolution.isSuccess()) { temp=getCurSol("X").toString()
						ForwardTime=temp.toLong()
						println("Settato forwardTime a $ForwardTime")
						 }
						solve("time(turnLeft,X)","") //set resVar	
						if(currentSolution.isSuccess()) { temp=getCurSol("X").toString()
						TurnLeftTime=temp.toLong()
						println("Settato turnLeftTime a $TurnLeftTime")
						 }
						solve("time(turnRight,X)","") //set resVar	
						if(currentSolution.isSuccess()) { temp=getCurSol("X").toString()
						TurnRightTime=temp.toLong()
						println("Settato turnRightTime a $TurnRightTime")
						 }
						solve("time(tuning,X)","") //set resVar	
						if(currentSolution.isSuccess()) { temp=getCurSol("X").toString()
						TuningTime=temp.toLong()
						println("Settato tuningTime a $TuningTime")
						 }
						solve("time(differenceLimit,X)","") //set resVar	
						if(currentSolution.isSuccess()) { temp=getCurSol("X").toString()
						DifferenceLimitTime=temp.toLong()
						println("Settato differenceLimitTime a $DifferenceLimitTime")
						 }
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("obstacle"), Term.createTerm("obstacle"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								endF = System.currentTimeMillis()
								replyToCaller("moveFailed","moveFailed")
						}
					}
					 transition(edgeName="t010",targetState="handleCmd",cond=whenDispatch("movementCmd"))
				}	 
				state("handleCmd") { //this:State
					action { //it:State
						storeCurrentMessageForReply()
						if( checkMsgContent( Term.createTerm("movementCmd(CMD)"), Term.createTerm("movementCmd(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								input=payloadArg(0)
								forward("moveReceived", "moveReceived" ,"movementhandler" ) 
						}
					}
					 transition(edgeName="to11",targetState="startForward",cond=whenDispatchGuarded("moveReceived",{input.equals("w")}))
					transition(edgeName="to12",targetState="startBacktracking",cond=whenDispatchGuarded("moveReceived",{input.equals("s")}))
					transition(edgeName="to13",targetState="startTurnLeft",cond=whenDispatchGuarded("moveReceived",{input.equals("a")}))
					transition(edgeName="to14",targetState="startTurnRight",cond=whenDispatchGuarded("moveReceived",{input.equals("d")}))
				}	 
				state("startForward") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,w)" ,"resourcemodelbutler" ) 
						startF = System.currentTimeMillis()
						stateTimer = TimerActor("timer_startForward", 
							scope, context!!, "local_tout_movementhandler_startForward", ForwardTime )
					}
					 transition(edgeName="t015",targetState="stopForward",cond=whenTimeout("local_tout_movementhandler_startForward"))   
					transition(edgeName="t016",targetState="waitCmd",cond=whenEvent("obstacle"))
				}	 
				state("stopForward") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,h)" ,"resourcemodelbutler" ) 
						replyToCaller("moveCompleted","moveCompleted")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("startTurnLeft") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,a)" ,"resourcemodelbutler" ) 
						stateTimer = TimerActor("timer_startTurnLeft", 
							scope, context!!, "local_tout_movementhandler_startTurnLeft", TurnLeftTime )
					}
					 transition(edgeName="t017",targetState="stopTurnLeft",cond=whenTimeout("local_tout_movementhandler_startTurnLeft"))   
				}	 
				state("stopTurnLeft") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,h)" ,"resourcemodelbutler" ) 
						replyToCaller("moveCompleted","moveCompleted")
						delay(1000) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("startTurnRight") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,d)" ,"resourcemodelbutler" ) 
						stateTimer = TimerActor("timer_startTurnRight", 
							scope, context!!, "local_tout_movementhandler_startTurnRight", TurnRightTime )
					}
					 transition(edgeName="t018",targetState="stopTurnRight",cond=whenTimeout("local_tout_movementhandler_startTurnRight"))   
				}	 
				state("stopTurnRight") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,h)" ,"resourcemodelbutler" ) 
						replyToCaller("moveCompleted","moveCompleted")
						delay(1000) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("startBacktracking") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						 TimeToWait=((endF-startF)-TuningTime).toLong()
						
									if(TimeToWait<DifferenceLimitTime)
										TimeToWait=0L
						println("###BACK PER $TimeToWait millis")
						forward("robotChange", "robotChange(robot,s)" ,"resourcemodelbutler" ) 
						stateTimer = TimerActor("timer_startBacktracking", 
							scope, context!!, "local_tout_movementhandler_startBacktracking", TimeToWait )
					}
					 transition(edgeName="t019",targetState="stopBacktracking",cond=whenTimeout("local_tout_movementhandler_startBacktracking"))   
				}	 
				state("stopBacktracking") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("robotChange", "robotChange(robot,h)" ,"resourcemodelbutler" ) 
						replyToCaller("moveCompleted","moveCompleted")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
