/* Generated by AN DISI Unibo */ 
package it.unibo.modelmanagerfridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Modelmanagerfridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[MODELMANAGER FRIDGE]: Started...")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("[MODELMANAGER MAITRE]: Sono in waitCmd")
					}
					 transition(edgeName="t060",targetState="handleCommand",cond=whenDispatch("stateChanged"))
					transition(edgeName="t061",targetState="handleCommand",cond=whenDispatch("dishUpdate"))
					transition(edgeName="t062",targetState="handleCommand",cond=whenDispatch("foodUpdate"))
				}	 
				state("handleCommand") { //this:State
					action { //it:State
						println("[MODELMANAGER MAITRE]: Sono in waitCmd")
						if( checkMsgContent( Term.createTerm("stateChanged(DEVICE,STATE)"), Term.createTerm("stateChanged(fridge,STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
						if( checkMsgContent( Term.createTerm("dishUpdate(DEVICE,QNT)"), Term.createTerm("dishUpdate(fridge,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
						if( checkMsgContent( Term.createTerm("foodUpdate(DEVICE,FOODCODE,QNT)"), Term.createTerm("foodUpdate(fridge,FOODCODE,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
