/* Generated by AN DISI Unibo */ 
package it.unibo.table

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Table ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var num = -1
				var fc = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[TABLE]: Started...")
						itunibo.table.tableSupport.create(  )
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						forward("modelUpdateTable", "modelUpdateTable(table,null,idle,null,null)" ,"resourcemodeltable" ) 
					}
					 transition(edgeName="t00",targetState="putElement",cond=whenDispatch("putElementTable"))
					transition(edgeName="t01",targetState="takeElement",cond=whenDispatch("takeElementTable"))
				}	 
				state("putElement") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("putElementTable(TYPE,FC,QNT)"), Term.createTerm("putElementTable(TYPE,FC,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelUpdateTable", "modelUpdateTable(table,${payloadArg(0)},put,${payloadArg(1)},${payloadArg(2)})" ,"resourcemodeltable" ) 
								
												fc=payloadArg(1)
												num=Integer.parseInt(payloadArg(2))
								if(payloadArg(0).equals("food"))
								itunibo.table.tableSupport.putFood(myself ,fc, num )
								if(payloadArg(0).equals("dish"))
								itunibo.table.tableSupport.putDish(myself ,num )
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("takeElement") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("takeElementTable(TYPE,FC,QNT)"), Term.createTerm("takeElementTable(TYPE,FC,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelUpdateTable", "modelUpdateTable(table,${payloadArg(0)},take,${payloadArg(1)},${payloadArg(2)})" ,"resourcemodeltable" ) 
								
												fc=payloadArg(1)
												num=Integer.parseInt(payloadArg(2))
								if(payloadArg(0).equals("food"))
								itunibo.table.tableSupport.takeFood(myself ,fc, num )
								if(payloadArg(0).equals("dish"))
								itunibo.table.tableSupport.takeDish(myself ,num )
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
