/* Generated by AN DISI Unibo */ 
package it.unibo.resourcemodelpantry

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Resourcemodelpantry ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[RESOURCEMODEL PANTRY]: Started...")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t01",targetState="handleChange",cond=whenDispatch("modelChangePantry"))
					transition(edgeName="t02",targetState="handleUpdate",cond=whenDispatch("modelUpdatePantry"))
				}	 
				state("handleChange") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("modelChangePantry(OP,QNT)"), Term.createTerm("modelChangePantry(OP,QNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelChangedPantry", "modelChangedPantry(${payloadArg(0)},${payloadArg(1)})" ,"pantry" ) 
								itunibo.pantry.resourceModelSupport.updatePantryModel(myself ,payloadArg(0) )
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("handleUpdate") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("modelUpdatePantru(OP)"), Term.createTerm("modelUpdatePantry(OP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								itunibo.pantry.resourceModelSupport.updatePantryModel(myself ,payloadArg(0) )
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
