/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("[FRIDGE]: starts...")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t03",targetState="checkCmd",cond=whenDispatch("check"))
				}	 
				state("checkCmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("check(FOODCODE)"), Term.createTerm("check(FOODCODE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val FC = payloadArg(0)
								forward("response", "response(FC,AMOUNT)" ,"robot" ) 
						}
					}
				}	 
			}
		}
}
